### ISSUE TITLE
There are no royalty-free sound effects

### ISSUE THREAD

**Issue by sjaks** [sjaks/vantaankosken-kalapuikko-js#1]
The original game has sounds that need to be copied or replicated. They do not have explicit licenses, so they are copyrighted.

Copying the original sounds would then require permissions from their author.

**Comment by elguitar** [comment]
I am interested in recording new sound files!

**Comment by Moppa5** [comment]
Especially the sound "Piipaapiipaa" need to be as authentic as possible.

**Comment by sjaks** [comment]
@elguitar please send the recordings in .ogg format. You can make a PR and put them directly into the `sounds` directory. :+1:

**Comment by elguitar** [comment]
What is the reasoning behind using `.ogg` format? Why not [Opus](https://en.wikipedia.org/wiki/Opus_(audio_format))?

**Comment by sjaks** [comment]
Isn't opus just a codec and works with the .ogg extension?

**Comment by sjaks** [comment]
@elguitar if you're interested, there's also this sound-related issue: https://github.com/sjaks/demooni/issues/15
